name: render eBook
on: [push]
jobs:
  render-ebook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#
    - uses: actions/upload-artifact@v4
      with:
        name: rendered-ebook
        path: result