name: Push rendered eBook to branch

on:
  workflow_run:
    workflows: ["render eBook"]  # Name of the primary workflow
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout the target branch
        uses: actions/checkout@v2
        with:
          ref: rendered

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: rendered-ebook

      - name: Commit and push artifacts
        run: |
	  unzip rendered-ebook.zip
          git add *.pdf
          git commit -m "Add artifacts from build"
          git push origin rendered
